config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.urls import path


urlpatterns = [
    path('', TemplateView.as_view(template_name='react.html')),
    url(r'^movies/', include('moviesapp.movies.urls', namespace='movies')),

    url(settings.ADMIN_URL, admin.site.urls),  # {% url 'admin:index' %}
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

moviesapp/movies/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'movies', views.MovieViewSet)
router.register(r'ratings', views.RatingViewSet)

app_name = 'moviesapp.movies'

urlpatterns = [
    url(r'^$', view=views.MovieListView.as_view(), name='index'),
    url(r'^(?P<pk>[\d]+)/$', view=views.MovieDetailView.as_view(), name='detail'),
    url(r'^create/$', view=views.MovieCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>[\d]+)/$', view=views.MovieUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>[\d]+)/$', view=views.MovieDeleteView.as_view(), name='delete'),
    url(r'^(?P<moviedId>[\d]+)/createRating/$', view=views.RatingCreateView.as_view(), name='createRating'),
    url(r'^(?P<moviedId>[\d]+)/updateRating/(?P<pk>[\d]+)/$', view=views.RatingUpdateView.as_view(), name='updateRating'),
    path('', include(router.urls))
]

moviesapp/movies/models.py
# -*- coding: utf-8 -*-
from django.urls import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Movie(models.Model):
    title = models.CharField(_('Movie\'s title'), max_length=255)
    year = models.PositiveIntegerField(default=2019)
    # Example: PG-13
    rated = models.CharField(max_length=64)
    released_on = models.DateField(_('Release Date'))
    genre = models.CharField(max_length=255)
    director = models.CharField(max_length=255)
    plot = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    # Todo: add Rating models

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movies:detail', kwargs={'pk': self.pk})

    def get_rating(self):
        return round(self.average_rating, 2) if self.average_rating else 'No rating yet'


class Rating(models.Model):
    BAD = 0
    NOT_GOOD = 1
    NEUTRAL = 2
    GOOD = 3
    VERY_GOOD = 4
    EXCELENT = 5
    RATES = (
        (BAD, _('Bad movie')),
        (NOT_GOOD, _('It is better not watch it')),
        (NEUTRAL, _('It is not good but it is not bad either')),
        (GOOD, _('Somehow good')),
        (VERY_GOOD, _('Good to see it')),
        (EXCELENT, _('Recommended')),
    )
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    value = models.IntegerField(choices=RATES, default=BAD)
    comment = models.TextField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('movies:detail', kwargs={'pk': self.movie.pk})

moviesapp/movies/views.py
# -*- coding: utf-8 -*-

"""Movies views."""

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404
from django.http import Http404
from django.urls import reverse_lazy, reverse
from django.db.models import Avg
from rest_framework import viewsets

from .models import Movie, Rating
from .serializers import MovieSerializer, RatingSerializer


class MovieListView(ListView):
    """Show all movies."""
    model = Movie


    def get_queryset(self):
        if 'title' in self.request.GET.keys():
            movies = Movie.objects.filter(title__startswith=self.request.GET['title']).annotate(average_rating = Avg('rating__value')).order_by('-released_on', 'average_rating')
        else:
            movies = Movie.objects.annotate(average_rating = Avg('rating__value')).order_by('-released_on', 'average_rating')

        return movies


class MovieDetailView(DetailView):
    """Show the requested movie."""
    model = Movie


class MovieCreateView(CreateView):
    """Create a new movie."""
    model = Movie
    fields = ['title', 'year', 'rated', 'released_on', 'genre', 
            'director', 'plot']


class MovieUpdateView(UpdateView):
    """Update the requested movie."""
    model = Movie
    fields = ['title', 'year', 'rated', 'released_on', 'genre', 
            'director', 'plot']


class MovieDeleteView(DeleteView):
    """Delete the requested movie."""
    model = Movie
    success_url = reverse_lazy('movies:index')

class RatingCreateView(CreateView):
    """Create a new movie."""
    model = Rating
    fields = ['value', 'comment']

    def get_context_data(self, **kwargs):
        """ Get context variables for rendering the template. """
        kwargs['movie'] = self.movie
        return super().get_context_data(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        """
        Overridden so we can make sure the `Movie` instance exists
        before going any further.
        """
        self.movie = get_object_or_404(Movie, pk=kwargs['moviedId'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """
        Overridden to add the movie relation to the `Rating` instance.
        """
        form.instance.movie = self.movie
        return super().form_valid(form)


class RatingUpdateView(UpdateView):
    """Update the requested movie."""
    model = Rating
    fields = ['value', 'comment']

    def get_context_data(self, **kwargs):
        """ Get context variables for rendering the template. """
        kwargs['movie'] = self.movie
        return super().get_context_data(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        """
        Overridden so we can make sure the `Movie` instance exists
        before going any further.
        """
        self.movie = get_object_or_404(Movie, pk=kwargs['moviedId'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """
        Overridden to add the movie relation to the `Rating` instance.
        """
        form.instance.movie = self.movie
        return super().form_valid(form)

class MovieViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows movies to be viewed or edited
    """
    queryset = Movie.objects.annotate(average_rating = Avg('rating__value')).order_by('-released_on', 'average_rating')
    serializer_class = MovieSerializer


class RatingViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows Rating to be viewed or edited
    """
    queryset = Rating.objects.all()
    serializer_class = RatingSerializer

moviesapp/templates/403_csrf.html
{% extends 'base.html' %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

moviesapp/templates/base.html
{% load staticfiles i18n %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% trans 'MoviesCRUDApp' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    {% block css %}
      <link href="{% static 'css/style.css' %}" rel="stylesheet">
      <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% endblock %}

    {% block javascript %}
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
      <!--[if lt IE 9]>
        <script src="js/respond.min.js"></script>
        <script src="js/html5shiv.min.js"></script>
      <![endif]-->
    {% endblock %}

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'img/django-logo.png' %}" width="80" alt="Django Framework"/></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
            <li class="active"><a href="{% url 'movies:index' %}">{% trans 'Movies' %}</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">

      {% if messages %}
        <div class="messages">
          {% for message in messages %}
            <p class="msg msg-{{ message.tags }}">{{ message }}</p>
          {% endfor %}
        </div>
      {% endif %}

      {% block content %}{% endblock %}

        <hr>
        <footer>
            <p>&copy; 2005 - {% now 'Y' %} {% blocktrans %}Django Software Foundation and individual contributors. Django is a registered trademark of the Django Software Foundation.{% endblocktrans %}</p>
        </footer>

    </div> <!-- /container -->

    {% block modal %}{% endblock %}

    {% block scripts %}{% endblock %}

  </body>
</html>


{% comment %}
  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">MoviesCRUDApp</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'movies:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>
{% endcomment %}

moviesapp/templates/movies/movie_confirm_delete.html
{% extends 'base.html' %} {% load static i18n %} {% block title %}{% trans
'Movie' %}: {% trans 'Delete' %}{% endblock %} {% block content %}

<h1>{{ object.title }}</h1>

<form
  class="form-horizontal"
  method="post"
  action="{% url 'movies:delete' object.pk %}"
>
  {% csrf_token %}
  {{ form.as_p }}
  <p>{% trans 'Are you sure you want to delete the movie?' %}</p>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">
        {% trans 'Yes, delete' %}
      </button>
    </div>
  </div>
</form>
{% endblock %}

moviesapp/templates/movies/movie_detail.html
{% extends 'base.html' %} {% load static i18n %} {% block title %}{% trans
'Movie' %}: {{ object.title }}{% endblock %} {% block content %}
<h3>{{ object.title }}</h3>
<div class="row">
  <div class="col-sm-12">
    <dl class="row">
      <dt class="col-sm-1">YEAR:</dt>
      <dd class="col-sm-4">{{ object.year }}</dd>
      <dt class="col-sm-1">RATED:</dt>
      <dd class="col-sm-6">{{ object.rated }}</dd>
      <dt class="col-sm-1">RELEASED:</dt>
      <dd class="col-sm-4">{{ object.released_on }}</dd>
      <dt class="col-sm-1">GENRE:</dt>
      <dd class="col-sm-6">{{ object.genre }}</dd>
      <dt class="col-sm-1">DIRECTOR:</dt>
      <dd class="col-sm-4">{{ object.director }}</dd>
      <dt class="col-sm-1">PLOT:</dt>
      <dd class="col-sm-6">{{ object.plot }}</dd>
    </dl>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
      <a href="{% url 'movies:createRating' object.pk %}">Add a Rating</a>
  </div>
</div>
{% for rating in object.rating_set.all %}
<div class="row">
  <div class="col-sm-1">
   <a href="{% url 'movies:updateRating' object.pk rating.pk%}">Edit</a>
  </div>
  <div class="col-sm-1">
    Rating:
  </div>
  <div class="col-sm-1">
    {{ rating.value }} out of 5
  </div>
  <div class="col-sm-1">
    Comment:
  </div>
  <div class="col-sm-8">
    {{ rating.comment }}
  </div>
</div>
{% endfor%}
{% endblock %}

moviesapp/templates/movies/movie_form.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Movie' %}{% endblock %}

{% block content %}
<h1>{{ object.title }}</h1>


<form class="form-horizontal" method="post" 
{% if 'create' in request.path %}
  action="{% url 'movies:create' %}"
{% else %}
  action="{% url 'movies:update' object.pk %}"
{% endif %}>
  {% csrf_token %}
  {{ form.as_p }}
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">
        {% if 'create' in request.path %}{% trans 'Create' %}{% else %}{% trans 'Update' %}{% endif %}
      </button>
    </div>
  </div>
</form>
{% endblock %}

moviesapp/templates/movies/movie_list.html
{% extends 'base.html' %} {% load static i18n %} {% block title %}{% trans
'Movies' %}{% endblock %} {% block content %}
<h3>{% trans 'Movies' %}</h3>
<div class="row">
  <div class="col-sm-12">
    <form action="{% url 'movies:index' %}" method="get">
      <input type="text" name="title" id="title" value="" />
      <input type="submit" value="Seach" />
    </form>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><b>Title</b></th>
       <th><b>Rating</b></th>
      <th colspan="2"><b>Actions</b></th>
    </tr>
  </thead>
  <tbody>
    {% for movie in movie_list %}
    <tr>
      <td><a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a></td>
      <td>{{ movie.get_rating }}</td>
      <td><a href="{% url 'movies:update' movie.pk %}">Edit</a></td>
      <td><a href="{% url 'movies:delete' movie.pk %}">Delete</a></td>
    </tr>
    {% endfor %}
    <tr>
      <td colspan="6"><a href="{% url 'movies:create' %}">Add new movie</a></td>
    </tr>
  </tbody>
</table>
{% endblock content %}

moviesapp/templates/movies/rating_form.html
{{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Movie' %}{% endblock %}

{% block content %}
<h1>{{ object.title }}</h1>


<form class="form-horizontal" method="post" 
{% if 'create' in request.path %}
  action="{% url 'movies:createRating' movie.pk %}"
{% else %}
  action="{% url 'movies:updateRating' movie.pk object.pk %}"
{% endif %}>
  {% csrf_token %}
  {{ form.as_p }}
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">
        {% if 'create' in request.path %}{% trans 'Create' %}{% else %}{% trans 'Update' %}{% endif %}
      </button>
    </div>
  </div>
</form>
{% endblock %}

moviesapp/templates/pages/home.html
{% extends 'base.html' %} {% load static i18n %}

<div class="jumbotron">
  <h1>{% blocktrans %}Welcome to Django Framework{% endblocktrans %}</h1>
  <p>
    {% blocktrans %}Congratulations! You have successfully installed the Movies
    CRUD App. You are currently running Django Framework.{% endblocktrans %}
  </p>
  <p>
    <a
      class="btn btn-success btn-lg"
      href="https://github.com/django/django"
      target="_blank"
      >{% blocktrans %}Fork Django on GitHub{% endblocktrans %} &raquo;</a
    >
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          {% blocktrans %}Follow Development{% endblocktrans %}
        </h3>
      </div>
      <div class="panel-body">
        <p>
          {% blocktrans %}Django is under active development...{% endblocktrans %}
        </p>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          {% blocktrans %}Discover Modules{% endblocktrans %}
        </h3>
      </div>
      <div class="panel-body">
        <p>{% blocktrans %}The community is working on...{% endblocktrans %}</p>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          {% blocktrans %}Help &amp; Support{% endblocktrans %}
        </h3>
      </div>
      <div class="panel-body">
        <p>
          {% blocktrans %}If you need any help or support while developing with
          Django, you may reach us via...{% endblocktrans %}
        </p>
      </div>
    </div>
  </div>
</div>

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include 'css.html' %}
    <title>Movies</title>
  </head>
  <body>
    <div class='container-fluid'>

        {% block content %}
            
        {% endblock content %}

    </div>  


    {% include 'js.html' %}
  </body>
</html>

templates/css.html
{% load static %}

<link rel='stylesheet' href="{% static 'css/2.47e06e2e.chunk.css' %}" />

templates/js.html
{% load static %}

<script src="{% static 'js/runtime-main.1c570d22.js' %}"></script>
<script src="/static/js/2.e5ca0e13.chunk.js"></script>
<script src="{% static 'js/react-movies.js' %}"></script>

templates/react.html
{% extends "base.html" %}

{% block content %}
    <div id='root'></div>
{% endblock content %}